### ISSUE TITLE
how to get/use this symfony check.php ?

### ISSUE THREAD

**Issue by sl5net** [symfony/requirements-checker#44]
if i start

http://localhost:8000/check.php

symfony tells me :

# Page not found

**Comment by StephanieDefresnes** [comment]
good question! composer is supposed to install this file in /public, isnt' it?
but none..

**Comment by dadaxr** [comment]
Same question here ... but after a quick digging here is what I found : 

In version >= 2.0 of this repo, web checker (public/checker.php) is not available anymore :  it was deleted in https://github.com/symfony/requirements-checker/commit/13ddc30afb3dd0fb0964dba4b2d17337f57b22e4. 

Since 2.0 this package was refactored to be used as a independent tool able to check many projects see :   https://github.com/symfony/requirements-checker/pull/43#issue-701658223

Of course you can still use version ^1.0 which provide public/checker.php

Actual Documentation should mention that ... PR welcome ;)

**Comment by dxshindeo** [comment]
Basically you have to read the `requirements-checker.php` file from console:

`php "D:\Projects\web\my-project\vendor\symfony\requirements-checker\bin\requirements-checker.php"`
